# Site settings
title: Morning Pulp
description: Wake up in the morning.
author: Cameron Tracy
url: http://morningpulp.com

# Build settings
baseurl: /jekyll
permalink: pretty
paginate: 5
markdown: rdiscount
rdiscount:
  extensions: [smart]
exclude: [.gitignore]