# Site settings
title: Morning Pulp
description: Wake up in the morning.
url: http://morningpulp.com

# Build settings
baseurl: /jekyll
permalink: pretty
markdown: rdiscount
rdiscount:
  extensions: [smart]
exclude: [.gitignore]