# Site settings
title: Morning Pulp
description: Wake up in the morning.
author: Cameron Tracy
url: http://morningpulp.com

# Build settings
baseurl: /jekyll
permalink: /:year/:month/:title
paginate: 5
markdown: kramdown
exclude: [.gitignore]
